[tool.poetry]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = ">=3.10.0,<3.12"
requests = "^2.31.0"
scipy = "^1.12.0"
dash = "^2.16.1"
dash-html-components = "^2.0.0"
dash-core-components = "^2.0.0"
dash-bootstrap-components = "^1.5.0"
pycountry = "^23.12.11"
numpy = "^1.26.4"
pandas = "^2.2.1"
plotly = "^5.19.0"
statsmodels = "^0.14.1"
researchpy = "^0.3.6"

[tool.pyright]
# https://github.com/microsoft/pyright/blob/main/docs/configuration.md
useLibraryCodeForTypes = true
exclude = [".cache"]

[tool.ruff]
# https://beta.ruff.rs/docs/configuration/
select = ['E', 'W', 'F', 'I', 'B', 'C4', 'ARG', 'SIM']
ignore = ['W291', 'W292', 'W293']

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"