[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true
packages = ["vertex"]

[project]
name = "isaric-vertex"
version = "1.0.0"
description = "Dash-based VERTEX dashboard for ISARIC"
authors = [
    { name = "Your Name", email = "you@example.com" }
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "boto3==1.39.1",
    "dash==2.16.1",
    "dash-bootstrap-components==1.5.0",
    "dash-core-components==2.0.0",
    "dash-html-components==2.0.0",
    "dash-table==5.0.0",
    "Flask==3.0.2",
    "Flask-SQLAlchemy==3.0.2",
    "Flask-Security-Too==5.6.2",
    "gunicorn",
    "importlib_metadata==7.0.2",
    "Jinja2==3.1.3",
    "lifelines==0.30.0",
    "numpy==1.26.4",
    "packaging==24.0",
    "pandas==2.2.1",
    "plotly==6.0.1",
    "psycopg2-binary==2.9.10",
    "pycountry==23.12.11",
    "requests==2.31.0",
    "scikit-learn==1.5.2",
    "scipy==1.12.0",
    "setuptools==74.1.2",
    "statsmodels==0.14.1",
]

[project.scripts]
run-vertex = "descriptive_dashboard:main"
